### ISSUE TITLE
Minimize layers count

### ISSUE THREAD

**Issue by lospejos** [LasLabs/docker-alpine-jira#2]
According to [https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#minimize-the-number-of-layers](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#minimize-the-number-of-layers) consider combine all RUN statements into the one:

Instead of 

`RUN exec1
RUN exec2`

do
`RUN exec1 && exec2`

Also don't forget to sort commands alphabetically to simplify further support.

**Comment by lasley** [comment]
Thanks for the advice @lospejos - this image has been updated in #3. I'll take a look at our other images and apply as well.
